# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e389aa30c03efec1a985b6effe6818baa0699610d0df7b88deeafa87d6a625e55350f985dd56b29852bad821da6c56aeb502ca6bdad9ee8b21accec64abc6b

test:
  secret_key_base: 658b240bec05b2538eac623d6279b3dbeaf6fa63f1585ab5da832d6b4b7cac983f3eeae874e2f28ca8e449b30cb31819011588c6485a6a4e1dad5e4bb7b487ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
